# Site settings
title: Huge Showcase
email: your-email@domain.com
description: "Showcase of huge widgets and js / css ideas and POC's" 
baseurl: ""
url: "http://hugeinc.com"

# Build settings
markdown: kramdown
permalink: pretty

paginate: 5
paginate_path: "page:num"
    
gems:
- jekyll-compass
