# Site settings
title: Huge Showcase
email: your-email@domain.com
description: "Showcase of huge widgets and js / css ideas and POC's"
baseurl: ""

# [wes] commenting out when working locally:
#url: "http://hugeinc.com"

# Build settings
markdown: kramdown
permalink: pretty

# [wes] temporarily commented out unitl we have more stuffs
paginate: 20
paginate_path: "page:num"

exclude: [
	".*",
	"Gemfile*"
]

gems:
- jekyll-compass

